CREATE TABLE solicitud (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo              VARCHAR(60) NOT NULL,
    fecha_inicio      TIMESTAMP WITH TIME ZONE NOT NULL,
    fecha_fin         TIMESTAMP WITH TIME ZONE NOT NULL,
    estado            VARCHAR(20) NOT NULL,
    comentario        VARCHAR(300),
    solicitante_email VARCHAR(120) NOT NULL,
    creado_en         TIMESTAMP WITH TIME ZONE NOT NULL
);