# =============================================================================
# DSY1107 - EA1 - Configuracion del backend.
#
# Todo lo de aqui se puede pisar con variables de entorno, que es como se
# configurara el dia que esto corra en un contenedor:
#
#   SERVER_PORT=9090
# =============================================================================

spring:
  application:
    name: ae1-backend

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://dsy1107-db-rivera.crgwtvlsw7oj.us-east-1.rds.amazonaws.com:5432/dsy1107?sslmode=require}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:Duoc2026Postgres}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:https://cognito-idp.us-east-1.amazonaws.com/us-east-1_xwRd4Qu4Z}

cognito:
  app-client-id: 5cg445kiro122rpc7g68jbna26

server:
  port: 8080
  error:
    include-message: always
    include-stacktrace: never

backend:
  cors:
    origenes:
      - http://localhost:4200
      - http://localhost:5173

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
      probes:
        enabled: false

logging:
  level:
    cl.duoc.dsy1107.ae1: DEBUG
